# docker latest python image
image: python


# TODO: add deployment stage to push automatically to pypi
stages:
  - test

# test source code formatting and tox testing
test:
  stage: test
  script:
    - pip install -r dev-requirements.txt
    - black --check pytijo tests
    - tox
